// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbBLV9XIppbJFz6zCJxgDzMD5fi7wRmxQ',
    appId: '1:219305378968:web:b133d3c27d547707fa7ced',
    messagingSenderId: '219305378968',
    projectId: 'fir-test-9b569',
    authDomain: 'fir-test-9b569.firebaseapp.com',
    storageBucket: 'fir-test-9b569.firebasestorage.app',
    measurementId: 'G-1MF9NGRWG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNhK3DkfhpZQSflJAxcAk27QxxZZkzCno',
    appId: '1:219305378968:android:a832bfc90d95d562fa7ced',
    messagingSenderId: '219305378968',
    projectId: 'fir-test-9b569',
    storageBucket: 'fir-test-9b569.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbBLV9XIppbJFz6zCJxgDzMD5fi7wRmxQ',
    appId: '1:219305378968:web:4ef394723d2996a8fa7ced',
    messagingSenderId: '219305378968',
    projectId: 'fir-test-9b569',
    authDomain: 'fir-test-9b569.firebaseapp.com',
    storageBucket: 'fir-test-9b569.firebasestorage.app',
    measurementId: 'G-DFLF2B4KMW',
  );
}
